### ISSUE TITLE
Knife tool is not working

### ISSUE THREAD

**Issue by Rub21** [mapbox/auto-tools#15]
https://josm.openstreetmap.de/ticket/13947#comment:2
https://josm.openstreetmap.de/ticket/13560#comment:7

cc. @samely

**Comment by samely** [comment]
The min version for JOSM has been [updated](https://github.com/mapbox/auto-tools/commit/7f9dbef9271910199043b3ed26c5a0ca47471a7c)

**Comment by don-vip** [comment]
This solves #13560 but I don't think #13947 (NPE) is fixed.

**Comment by samely** [comment]
It's fixed now.
https://github.com/mapbox/auto-tools/pull/18

**Comment by Klumbumbus** [comment]
Seems not fixed. New error with same NPE in https://josm.openstreetmap.de/ticket/16221
