### ISSUE TITLE
NPE in ReplaceBuilding.java

### ISSUE THREAD

**Issue by BathoryPeter** [mapbox/auto-tools#16]
Selected two building, and pushed ReplaceBuildings button.

```
Thread: AWT-EventQueue-0 (17) of main
java.lang.NullPointerException
	at org.openstreetmap.josm.plugins.auto_tools.actions.ReplaceBuilding.getTagConflictResolutionCommands(ReplaceBuilding.java:136)
	at org.openstreetmap.josm.plugins.auto_tools.actions.ReplaceBuilding.buildReplaceWayCommand(ReplaceBuilding.java:304)
	at org.openstreetmap.josm.plugins.auto_tools.actions.ReplaceBuilding.buildReplaceWayWithNewCommand(ReplaceBuilding.java:284)
	at org.openstreetmap.josm.plugins.auto_tools.actions.ReplaceBuilding.buildReplaceWithNewCommand(ReplaceBuilding.java:117)
	at org.openstreetmap.josm.plugins.auto_tools.actions.ReplaceBuilding.actionPerformed(ReplaceBuilding.java:101)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:833)
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:877)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6533)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
}}}
```

**Comment by samely** [comment]
Hi @BathoryPeter I've updated the plugin, not sure if that fix this problem since I couldn't replicate that scenario. Can you try it again? 
Thanks!

**Comment by BathoryPeter** [comment]
Hi samely, thanks for the update! Unfortunately the bug is still there. I've created a test file with an existing and a new building. When I select both of them and click on ReplaceBuilding, I get the error dialog. (Latest JOSM, clean .josm dir, only enabled auto_tools and utilsplugin2.)

https://gist.github.com/BathoryPeter/e984799e2cc2447788e1576798d007c1

**Comment by samely** [comment]
Oh! yup. It is due to one of the objects doesn't have `building=yes` tag. Thanks for your feedback, I will let you know when I fixed it.

**Comment by samely** [comment]
Hi @BathoryPeter, sorry for my late response. I've fixed this bug, can you try it again and close this ticket if it works?
Thanks
